# Generated by Django 4.0.1 on 2022-01-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name_en', models.CharField(max_length=50)),
                ('prod_desc_en', models.CharField(max_length=75)),
                ('prod_class_en', models.CharField(max_length=75)),
                ('prod_name_ta', models.CharField(max_length=50)),
                ('prod_desc_ta', models.CharField(max_length=75)),
                ('prod_class_ta', models.CharField(max_length=75)),
            ],
        ),
    ]
